name: Host - Recaptcha Rooms - Group 3

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: haxball-recaptcha-hosts-group3
  cancel-in-progress: false

jobs:
  run-script:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 15
      matrix:
        include:
          - recaptcha_token: "thr1.AAAAAGotilCcc5N-HHrIqg.vwKP89YOfzU"
            index: 0
          - recaptcha_token: "thr1.AAAAAGotilt7PQW3CuBAuQ.jZnmVKI4Za4"
            index: 1
          - recaptcha_token: "thr1.AAAAAGotimUBVXZ_Co2dEw.SOIyqkNk2bQ"
            index: 2
          - recaptcha_token: "thr1.AAAAAGotim9dYqBI8luPdw.hZ25xtLeK_w"
            index: 3
          - recaptcha_token: "thr1.AAAAAGotinsgf4UthVdHyw.R7NnAbICZFk"
            index: 4
          - recaptcha_token: "thr1.AAAAAGotioYd-d0ooyvGPw.t2Nbe1r-YxU"
            index: 5
          - recaptcha_token: "thr1.AAAAAGotipEWpf2vR37KsA.peViXXFgmeE"
            index: 6
          - recaptcha_token: "thr1.AAAAAGotiqSIyImjL5Yilg.frFHum_Izbg"
            index: 7
          - recaptcha_token: "thr1.AAAAAGotirAkmu-I0P2YYQ.22-D6V9iB2o"
            index: 8
          - recaptcha_token: "thr1.AAAAAGotiryBtIT1XeCytw.-I_Go9FyNrQ"
            index: 9
          - recaptcha_token: "thr1.AAAAAGotisfi25E0gwXjFA.-idsBDKJOP0"
            index: 10
          - recaptcha_token: "thr1.AAAAAGotitfPBTO9hA4rcA.G3-XKtLh3jc"
            index: 11
          - recaptcha_token: "thr1.AAAAAGotiuaGyO9XLaSNFQ.2i9ktsElAS8"
            index: 12
          - recaptcha_token: "thr1.AAAAAGotivFyD6mfb8Wj1g.2gvOqnDgifA"
            index: 13

    steps:
      - name: 🧩 Checkout repo
        uses: actions/checkout@v4

      - name: 🧹 Limpiar entorno previo
        run: rm -rf node_modules package-lock.json

      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 📦 Instalar dependencias
        run: npm install

      - name: 🚀 Ejecutar host
        run: node hosts.js
        env:
          INDEX: ${{ matrix.index }}
          RECAPTCHA_TOKEN: ${{ matrix.recaptcha_token }}
          ROOM_PASSWORD: ""
          PLAYER_NAME: "Teleese"
          PLAYER_AVATAR: "👽"
